name: Auto Merge PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      - name: Merge PR
        run: |
          # Determine target branch from PR
          TARGET_BRANCH=${{ github.event.pull_request.base.ref }}
          
          # Fetch the target branch and check it out
          git fetch origin $TARGET_BRANCH
          git checkout $TARGET_BRANCH
          
          # Merge the PR branch into the target branch
          git merge ${{ github.event.pull_request.head.ref }} --no-edit
          
          # Push the changes back to the target branch
          git push origin $TARGET_BRANCH
